Fix deprecation error. HelpEntry had a user defined copy constructor (that was never used). For correctness, this implies that also a user defined or explicitly deleted operator= is required, but it was not defined. Deleted the unused copy constructor got rid of this error.
Error was:
src/editor/ui_menus/editor_help.h:48:3: error: definition of implicit copy assignment operator for 'HelpEntry' is deprecated because it has a user-declared copy constructor [-Werror,-Wdeprecated]